### ISSUE TITLE
design architecture

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/d2-docker#1]

**Comment by tokland** [comment]
## Workflow:

docker data-only image: dhis2-MAL 

- Base tag: 2.30 (with common orgUnits tree)
- Template tags: 2.30-ento, 2.30-epi, 2.30-ento-epi
- Template+Country tags: 2.30-ento-tanzania, 2.30-epi-mali

### Pull and modify images

Use a 1:1 image<-> container mapping. Example: image=eyeseetea/dhis2-MAL:2.30-epi-tanzania -> container=eyeseetea-dhis2-MAL-2-30-epi-tanzania

```
$ bin/d2-docker start eyeseetea/dhis2-MAL:2.30-epi # autoselect port: 8080 and up.
# http://localhost:8080 working -> change metadata
$ docker commit eyeseetea/dhis2-MAL:2.30-epi # Without argument, find the one runnning and use it
$ docker push eyeseetea/dhis2-MAL:2.30-epi # Without argument, same.
```

To search the current, check output of `docker ps`, If many matches, show error:

## Copy (Backup/restore DB)

Source [1]: docker / dump.sql / postgres-uri
Target [N]: docker / dump.sql / postgres-uri

```
bin/d2-docker copy [OPTIONS] SOURCE [DEST...]
```

Example

```
bin/d2-docker copy \
    --clean-history # this uses docker export, docker import (otherwise, just normal push)
    --push-images
    --keep-alive | --stop-containers
    --post-sql=custom.sql
    output-dump.sql.gz \
    eyeseetea/dhis2-MAL:2.30-epi-tanzania \
    postgres://USER:PASSWORD@HOSTNAME:PORT \
    eyeseetea/dhis2-MAL:2.30-epi-kenia
```

Copy sql file https://github.com/EyeSeeTea/ESTools/blob/master/DHIS2/cloner/empty_data_tables_228.sql

### Export / import using a single file

Headquarters:

```
$ bash d2-docker export \
    eyeseetea/dhis2-MAL:2.30-epi-tanzania \
    dhis2-epi-tanzania.tgz
```

Field:

```
$ bash d2-docker start dhis2-epi-tanzania.tgz
```

### Dependencies:

- docker
- docker-compose
- python
- postgres (psql/pg_dump)

## Implementation

- *docker-compose*: Use original 3 services from dhis2/docker-compose + psql-data-only service (copy from container to shared volume)
- Implement wrapper scripts with python (reuse dhis2api.py from cloner)


## Docs

https://docs.google.com/document/d/1WYvJhAOxznpRvl0wxGOpJq70TEgtqvVKB3luE2wRA74/
